import * as fs from 'fs'
import * as path from 'path'

// ---------------------------------------------------------------------------
// Config — add or remove folders here as needed
// ---------------------------------------------------------------------------
const ASSET_DIRS: { dir: string; category: string }[] = [
  { dir: 'src/assets/blocks',      category: 'block'      },
  { dir: 'src/assets/backgrounds', category: 'background' },
  { dir: 'src/assets/props',       category: 'prop'       },
]

const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg'])
const LOCK_FILE   = 'sprites.lock.json'
const OUTPUT_FILE = 'src/data/generated/sprites.ts'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
type SpriteLock = Record<string, number> // spritePath -> stable id

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function fileNameToDisplayName(filename: string): string {
  return path.parse(filename).name
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function loadLock(): SpriteLock {
  if (fs.existsSync(LOCK_FILE)) {
    return JSON.parse(fs.readFileSync(LOCK_FILE, 'utf-8'))
  }
  return {}
}

function saveLock(lock: SpriteLock): void {
  fs.writeFileSync(LOCK_FILE, JSON.stringify(lock, null, 2), 'utf-8')
}

function nextAvailableId(lock: SpriteLock): number {
  const ids = Object.values(lock)
  return ids.length > 0 ? Math.max(...ids) + 1 : 1
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
interface SpriteEntry {
  id: number
  name: string
  sprite: string
  category: string
}

function collectEntries(): SpriteEntry[] {
  const lock = loadLock()
  let idCounter = nextAvailableId(lock)
  let lockDirty = false
  const entries: SpriteEntry[] = []

  for (const { dir, category } of ASSET_DIRS) {
    if (!fs.existsSync(dir)) {
      console.warn(`⚠️  Skipping missing directory: ${dir}`)
      continue
    }

    for (const file of fs.readdirSync(dir).sort()) {
      if (!IMAGE_EXTENSIONS.has(path.extname(file).toLowerCase())) continue

      const spritePath = path.join(dir, file).replace(/\\/g, '/')

      // New file → assign a brand-new ID that will never be reused
      if (lock[spritePath] === undefined) {
        lock[spritePath] = idCounter++
        lockDirty = true
        console.log(`🆕  id ${lock[spritePath]}  ←  ${spritePath}`)
      }

      entries.push({
        id:       lock[spritePath],
        name:     fileNameToDisplayName(file),
        sprite:   spritePath,
        category,
      })
    }
  }

  if (lockDirty) {
    saveLock(lock)
    console.log(`🔒  Lock updated → ${LOCK_FILE}`)
  }

  entries.sort((a, b) => a.id - b.id)
  return entries
}

function render(entries: SpriteEntry[]): string {
  const lines = entries.map(
    e => `  { id: ${e.id}, name: '${e.name.replace(/'/g, "\\'")}', sprite: '${e.sprite.replace(/'/g, "\\'")}', category: '${e.category}' },`
  )
  
  return [
    `// AUTO-GENERATED by generate-sprites.ts — do not edit manually`,
    `// Run: npx tsx generate-sprites.ts`,
    `import type { Item } from '../types'`,
    ``,
    `export const items: Item[] = [`,
    ...lines,
    `]`,
    ``,
  ].join('\n')
}

const entries = collectEntries()

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
fs.writeFileSync(OUTPUT_FILE, render(entries), 'utf-8')

console.log(`✅  ${entries.length} sprites → ${OUTPUT_FILE}`)